### ISSUE TITLE
Discussion - Software Deployment

### ISSUE THREAD

**Issue by LaurenceLeo** [hezmondo/Jinn#121]
Currently there is no easy way for a user to upgrade their Jinn code. This means that rolling out our changes requires a lot of input from us and likely causes some unease in the users. Automating deployment seems crucial now that we are making a lot of changes to functionality in the software. I think it is important that the users have confidence that any suggested changes that we make can be obtained easily, with as little work on their end as possible.

I have seen a method for this that would require all users to have "Git" installed on their machines. We can then create a .bat file that will perform a pull from the Master branch. 
https://stackoverflow.com/questions/26016306/run-batch-file-with-git-pull-in-gitbash

We could also rename HJinn to Test/Development. Merging any new functionality from it into Master. 

I would particularly like Jonathan's input on this as he has experience in the industry.
P.S. Sorry if any of this is unclear, I will clarify if needed.

**Comment by LaurenceLeo** [comment]
I am extremely excited to try this. I think it will make our lives so much easier!!! :D

**Comment by jnbarchan** [comment]
Done.
Invoke with `Jinn`, not `Jinn/Code`, as the current directory:
`python3 Code/updatejinn.py`
You can optionally specify a *branch name* as extra argument on the command-line, e.g.
`python Code\updatejinn.py HJinn`
to use that `github` branch name instead of the default `master`.

**Comment by jnbarchan** [comment]
Changed so that instead of relying on the current directory being the `Jinn` level, instead it locates the `Code` folder from the directory in which `updatejinn.py` script file being run is located.  Jinn does it this way.  It means we do not have to rely on the current directory (e.g. what about if `Jinn\Code` is on a UNC?), the current directory can be anywhere (though not within `Jinn/Code` as explained above) and the path to `updatejinn.py` can be specified.
