### ISSUE TITLE
Interesting challenge on rent page statement button

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#150]
Currently, clicking the "Statement" button on the rent page and putting in any date a few years ago (to define the report period) throws an error because we are no longer using Win32.com.  Whether we use writetocsv or openpyxl to get the data into a spreadsheet is not the hard part, which is to provide the correct data.

The challenge to provide a detailed report showing all amounts which fell due in the period as debits in one column and all income allocations received in the period as credits in another column, with any difference shown as a deficit or surplus at the end of the sheet.

* It is easy to iterate (and debit) each gale of rent, the date it fell due and whether in advance or arrears using annual rent, frequency, datecode and advarr.
* Equally easy is to correctly deal with (and credit) all income allocations of ChargeType = 1 (rent).
* The tricky bit is how to deal with income allocations with ChargeType != 1. 
* I am assuming that any unallocated payments (chargetype = 2) can simply be shown as unallocated credits on the sheet.
* I am assuming that any fully cleared income allocation with chargetype > 2 can be dealt with by placing a credit and an equal debit into the sheet with the same date, being the PayDate for the associated income record.
* This leaves us needing to deal correctly with any charge that remains outstanding either in full or part.  I am assuming we can simply show the whole of the original charge amount as a debit with the date being chargestartdate and any part payments (income allocations towards this charge) as individual credits with respective paydates.

This leaves one remaining challenge (which eluded Billy and Taran), which is to present all the rows in chronological order and nicely laid out.

I welcome any input as to the best way to solve this challenge.  I will be happy to help with the openpyxl bit, if we need this, once we have the correct data in python.

**Comment by jnbarchan** [comment]
Started out by making this work under Windows, using `openpyxl`.  (This gets rid of last code to invoke Excel; soon we will be able to get rid of `win32comClientDispatch()`.)

Now I need to know just what is wrong/not good enough/needs doing, given a good example....

**Comment by jnbarchan** [comment]
* Refactored existing code stab attempt.

* Corrected the computation of charges to be shown as per complex instructions from H.

* Put comments into code to explain how each of the 3 "[logical] columns" (rents/charges/payments) actually get their data from the data tables.

* Changed output rows to "interleave" entries in all 3 columns by combined data order ascending, as requested.  So now every row contains just one transaction, and you read down the sheet in date order.  So it's like a bank statement.

* Added in a "running balance" final column, since we can do that now, again like a bank statement.

* Changed so that statement dialog is now invoked with default start date of 5 years ago today.

**Comment by jnbarchan** [comment]
I have changed the statement format over to what H. specified above.

In doing so it has all been refactored so that the work is no longer done by explicit, dedicated code in `statement.py`.  Instead that now generates a temporary table/model for what it wants and then calls `TableModelExporter.exportToCsv()` to export to CSV/XLSX.  This makes it like anywhere else where you can export from a `JTableView` via context menu.  Like that the user is now given a choice of either CSV or XLSX (we may remove CSV at a future date); it no longer creates both a `.csv` and a `.xlsx`.

I could still maybe do with some refactoring of `TableModelExporter` class to separate out CSV/XLSX ("spreadsheet") from PDF/DOCX/HTML ("text") exporters into distinct sub-classes, but that's for another day....
