### ISSUE TITLE
DocX files should NOT be used as attachments!!!

### ISSUE THREAD

**Issue by LaurenceLeo** [hezmondo/Jinn#165]
Our current method of saving DocX files means that they can **only** be opened using Libre Office. Although this is fine for our users, since we have ensured that they all have Libre Office installed, it is not fine for anyone else. I can confirm that Microsoft Word 2013 **cannot** open these documents. 

Since we are on the verge of integrating multiple emailed pay requests I have just realised we may allow users to email documents that recipients will probably be **unable to open!** 

We can solve this by blocking the option to email DocX files. I am open to any other suggestions.

(I can see HMCC performing a run of hundreds of DocX pay requests and having quite a bad time...)

**Comment by jnbarchan** [comment]
Is there a good reason why you want to send people these pay request documents as any kind of `.doc` file?  Personally I would not welcome receiving anything from anybody as a Word-type attachment, I'd be too concerned about viruses.  Would changing over to `.pdf` attachments always be acceptable/a good idea?

Otherwise, yes, someone needs to think these requirements through carefully before they are specified/implemented....

**Comment by LaurenceLeo** [comment]
Hes has informed me that the users have been told not to use this. I'll leave it open since it might be a pitfall we have to deal with at some point.
