### ISSUE TITLE
rentpage: deeds info line edit seems to display right aligned?

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#231]
rentpage: deeds info line edit seems to display right aligned?  Or, have I done something?

All our other line edits are left aligned, so it would make sense for this one to behave likewise

**Comment by jnbarchan** [comment]
This only happens if the text exceeds the width of the `QLineEdit`.  This is not really "right aligned".  This applies to every `QLineEdit`, not this specific one.

Code simply goes `QLineEdit.setText()`.  Qt system treats that as though user had typed in.  If you were to type a long line like this, as you typed at end it would have scrolled the left-hand edge off to accommodate.  It's either a Qt behaviour, or a default windowing system behaviour.  *This* is the reason for the scrolled situation.

To remedy: we would have to do something about overriding our `JLineEdit.setText()` to follow it with a `JLineEdit.setCursor(0)`.  But there are perhaps other methods which might also need looking at?  I have actually done the `setCursor(0)` explicitly in a couple of cases where I noticed long text like this.  I would want/suggest a consistent solution to all if decide to do it.

H.: have a look around and see if this is happening in lots of places and is annoying you.  Let me know/re-assign to me if you *do* want this done.

**Comment by jnbarchan** [comment]
I had a look at other apps.  At least under Windows it seems the "standard" is to display edit controls whose text exceeds the width as left-scrolled, not right-scrolled (i.e. at the start, not end).

So I made `JLineEdit` (all our uses of Qt `QLineEdit` go through this) override `setText()` to include a `setCursorPosition(0)`.  Removed anywhere we currently explicitly set that in a few places where we happened to notice the text was long, there is no longer any need to do that.  I *trust* there are no funny places where this changes behaviour we care about.
