### ISSUE TITLE
Table headings are inconsistently emboldened when an item is selected

### ISSUE THREAD

**Issue by LaurenceLeo** [hezmondo/Jinn#233]
Currently when we select an item in a table the column headings are emboldened. Emboldened headings seem to relate to the selection behaviour of the table. For example: if a row selection is made all headings are emboldened, if a single column is selected only that column heading is emboldened. 

This is **not** the case for the **cases** table for some reason. This is also causing issues as it makes the headings larger, so in some cases they are no longer readable.

**Comment by jnbarchan** [comment]
> This is not the case for the cases table for some reason. 

Note: it *is* the case that headings go bold under Linux for *all* tables, including the **Cases** one, so that bit seems like an odd Windows issue?

**Comment by LaurenceLeo** [comment]
Yep this seems to be a Windows issue.

**Comment by LaurenceLeo** [comment]
It seems the cause of this weird behaviour is in **widgets\layoutfunctions.py**, in the method **loadColumnLayout**.  It seems to have something to do with the QSettingsJinn.value and whether or not the columns need to be reloaded. 

The behaviour seems to be caused in casespage.py by:

loadData>self.loadColumnLayout()>self.loadDefaultColumnLayout()

It is evident that this is the cause if you comment out self.loadColumnLayout() at line 209.

I'll have another look later, but would be very interested in what **J** makes of this.

**Comment by jnbarchan** [comment]
I am dealing with this.

I don't know any relevance to `loadColumnLayout()` or `loadDefaultColumnLayout()`.  I don't know whether L.'s comment pertains to the emboldening of columns on all tables or only on the **Cases** page.  It doesn't help that unmder Linux I see no special handling for the **Cases** page.

However, I don't think we care about the above.  This whole emboldening of table headers in response to selections is something I have not seen in native Windows/Linux apps.  We do not want it for our users, and it only causes problems by changing the column header width.

The emboldening behaviour is controlled by https://doc.qt.io/qt-5/qheaderview.html#highlightSections-prop.  That states the default is *false*.  However as per https://stackoverflow.com/questions/1487375/qt-stylesheets-qheaderview-draws-header-text-in-bold-when-view-data-is-selected and https://bugreports.qt.io/browse/QTBUG-13783 it appears this is a documentation bug: for unknown reason, in a `QTableView` it defaults to *true*.

Made our `JTableView` set it to false, since that's what we want (at least by default).
