### ISSUE TITLE
ComboFilter "Dropdowns/Views" are unreadable 

### ISSUE THREAD

**Issue by LaurenceLeo** [hezmondo/Jinn#248]
Some of our filter dropdown lists are currently not wide enough to display our selections properly. The best example of this is our **Landlord** filter on the **MPR Selected Run** page.  This doesn't seem to be an issue on Linux and has only been noticed on Windows operating systems.

The solution to this seems simple:
Obtain the **view** that is used by the ComboBox and use setMinimumWidth() to increase the width to the same size as our largest list item. This is done as follows:

view = combo.view()
# Obtain combo widget font so we can determine screen usage
comboFont = combo.fontMetrics()
itemWidth = comboFont.width(item)
# Set view width to screen usage by "item"
view.setMinimumWidth(itemWidth)

Unfortunately at the moment we use multiple different functions to set values for our **JComboBox** otherwise we could just alter the **JComboBox** method **setCurrentText**. 

It might be worth refactoring the Combo\Filter code for method **addItem** so that we can alter the behaviour of all comboBoxes.

**Comment by jnbarchan** [comment]
Have you read Fix #215, which is why this shortening behaviour was deliberately introduced?  Have you considered how it looks with full width, not just for your usage but instead for users who run with a much narrower desktop or choose not to make the Jinn window anywhere near full screen size?

In any case, none of the above is necessary.  We do not need to measure item widths and then set combo minimum width to that.  The old/original/default behaviour is and always has been that a combobox automatically sets its width to that of the longest item if you do *not* specific a minimum width, which is what it used to be.  And looks pretty ugly IMHO.

If you wish to petition H. to restore to old behaviour that is the way to go.  But the filters may become unusable if, say, your database has long landlord names etc. ...

**Comment by LaurenceLeo** [comment]
This does not effect the actual length of the combobox widgets. It just increases the size of the dropdowns that open. Since only one can be open at a time I do not really see the issue.

**Comment by jnbarchan** [comment]
> It just increases the size of the dropdowns that open.

If that is so it is what I have been asking about for days on the Qt forum.  Nobody there has mentioned this possibility.  I will investigate.

**Comment by LaurenceLeo** [comment]
To do it we work get the view being diplayed by the **QComboBox**:
view = combo.view()

The work out the screen space using QFontMetrics and our string display.
Then we set the view size alone, **not the QComboBox**.
view.setMinimumSize()

this results in the dropdown alone being resized based upon the interpreted user font and screenspace used by the item in the view.

**Comment by jnbarchan** [comment]
Yes, I understand this.  Thank you for discovering how it can be achieved.  I will implement in an appropriate fashion next thing after my current work.

**Comment by jnbarchan** [comment]
Done.  Correctly in `JComboBox.showPopup()`, so don't have to worry with how we populate the combos.
