### ISSUE TITLE
Add two preview buttons to editletter.dialog

### ISSUE THREAD

**Issue by hezmondo** [hezmondo/Jinn#83]
As discussed with Jonathan, it will be a great improvement to the edit letter function if we can add two new buttons to appear in the bottom HBox (self.buttonsLayout) between the Save button and the Cancel button:

"Preview letter" will display the fully merged and interpreted letter version of the letter in an html preview screen which will not allow any editing - it will simply have a Close button.

"Preview email" will display the fully merged and interpreted email version of the letter in an html preview screen which will not allow any editing - it will simply have a Close button.

In all cases, the data will be the relevant data for the current rent page open in Jinn and we will bypass the currently used intermediate dialog, using the default values for that dialog.

**Comment by jnbarchan** [comment]
As discussed, the preview will need to reflect the editing changes the user is making.  Since it's going to be hard/messy to pass those Clauses around as parameters, we will insist the letter must be saved before it can be previewed.  The **Save** button will need to leave the user in the Edit Letter dialog instead of exiting it as it does now.
